CREATE OR REPLACE VIEW SHIPPING_DB.REPORTS.V_AVERAGE_SHIPPING_TIME AS
SELECT
    sm.SHIP_MODE,
    COUNT(f.ORDER_ID)                                                   AS TOTAL_ORDERS,
    ROUND(AVG(f.SHIPPING_DURATION), 2)                                  AS AVG_SHIPPING_DAYS,
    ROUND(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY f.SHIPPING_DURATION), 2) AS MEDIAN_SHIPPING_DAYS,
    MIN(f.SHIPPING_DURATION)                                            AS MIN_SHIPPING_DAYS,
    MAX(f.SHIPPING_DURATION)                                            AS MAX_SHIPPING_DAYS
FROM SHIPPING_DB.GOLD.FACT_SHIPPING       f
INNER JOIN SHIPPING_DB.GOLD.DIM_SHIP_MODE sm ON f.SHIP_MODE_KEY = sm.SHIP_MODE_KEY
GROUP BY sm.SHIP_MODE;

CREATE OR REPLACE VIEW SHIPPING_DB.REPORTS.V_DELAYED_ORDERS AS
SELECT
    f.ORDER_ID,
    od.FULL_DATE                                                        AS ORDER_DATE,
    sd.FULL_DATE                                                        AS SHIP_DATE,
    sm.SHIP_MODE,
    op.ORDER_PRIORITY,
    l.REGION,
    l.COUNTRY,
    f.SHIPPING_DURATION,
    f.SHIPPING_DURATION_MEDIAN_BY_MODE,
    (f.SHIPPING_DURATION - f.SHIPPING_DURATION_MEDIAN_BY_MODE)          AS EXCESS_DAYS,
    f.SHIPPING_COST
FROM SHIPPING_DB.GOLD.FACT_SHIPPING            f
INNER JOIN SHIPPING_DB.GOLD.DIM_DATE           od ON f.ORDER_DATE_KEY     = od.DATE_KEY
INNER JOIN SHIPPING_DB.GOLD.DIM_DATE           sd ON f.SHIP_DATE_KEY      = sd.DATE_KEY
INNER JOIN SHIPPING_DB.GOLD.DIM_SHIP_MODE      sm ON f.SHIP_MODE_KEY      = sm.SHIP_MODE_KEY
INNER JOIN SHIPPING_DB.GOLD.DIM_ORDER_PRIORITY op ON f.ORDER_PRIORITY_KEY = op.ORDER_PRIORITY_KEY
INNER JOIN SHIPPING_DB.GOLD.DIM_LOCATION        l ON f.LOCATION_KEY       = l.LOCATION_KEY
WHERE f.IS_DELAYED = TRUE;

CREATE OR REPLACE VIEW SHIPPING_DB.REPORTS.V_REGION_PERFORMANCE AS
SELECT
    l.REGION,
    l.COUNTRY,
    COUNT(f.ORDER_ID)                                                   AS TOTAL_ORDERS,
    ROUND(AVG(f.SHIPPING_DURATION), 2)                                  AS AVG_SHIPPING_DURATION,
    ROUND(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY f.SHIPPING_DURATION), 2) AS MEDIAN_SHIPPING_DURATION,
    SUM(CASE WHEN f.IS_DELAYED THEN 1 ELSE 0 END)                       AS DELAYED_ORDERS,
    ROUND(SUM(CASE WHEN f.IS_DELAYED THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(f.ORDER_ID), 0), 2) AS DELAY_RATE_PCT,
    ROUND(AVG(f.SHIPPING_COST), 2)                                      AS AVG_SHIPPING_COST,
    ROUND(SUM(f.SHIPPING_COST), 2)                                      AS TOTAL_SHIPPING_COST
FROM SHIPPING_DB.GOLD.FACT_SHIPPING   f
INNER JOIN SHIPPING_DB.GOLD.DIM_LOCATION l ON f.LOCATION_KEY = l.LOCATION_KEY
GROUP BY l.REGION, l.COUNTRY;

CREATE OR REPLACE VIEW SHIPPING_DB.REPORTS.V_SHIPPING_MODE_DISTRIBUTION AS
SELECT
    sm.SHIP_MODE,
    COUNT(f.ORDER_ID)                                                   AS TOTAL_ORDERS,
    ROUND(COUNT(f.ORDER_ID) * 100.0 / SUM(COUNT(f.ORDER_ID)) OVER (), 2) AS ORDER_SHARE_PCT,
    ROUND(AVG(f.SHIPPING_COST), 2)                                      AS AVG_SHIPPING_COST,
    ROUND(SUM(f.SHIPPING_COST), 2)                                      AS TOTAL_SHIPPING_COST,
    ROUND(AVG(f.SHIPPING_DURATION), 2)                                  AS AVG_SHIPPING_DAYS,
    SUM(CASE WHEN f.IS_DELAYED THEN 1 ELSE 0 END)                       AS DELAYED_ORDERS,
    ROUND(SUM(CASE WHEN f.IS_DELAYED THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(f.ORDER_ID), 0), 2) AS DELAY_RATE_PCT
FROM SHIPPING_DB.GOLD.FACT_SHIPPING       f
INNER JOIN SHIPPING_DB.GOLD.DIM_SHIP_MODE sm ON f.SHIP_MODE_KEY = sm.SHIP_MODE_KEY
GROUP BY sm.SHIP_MODE;
