SELECT
    f.ORDER_ID,
    od.FULL_DATE                                                AS ORDER_DATE,
    sd.FULL_DATE                                                AS SHIP_DATE,
    sm.SHIP_MODE,
    op.ORDER_PRIORITY,
    l.REGION,
    l.COUNTRY,
    f.SHIPPING_DURATION,
    f.SHIPPING_DURATION_MEDIAN_BY_MODE,
    (f.SHIPPING_DURATION - f.SHIPPING_DURATION_MEDIAN_BY_MODE)  AS EXCESS_DAYS,
    f.SHIPPING_COST
FROM GOLD.FACT_SHIPPING             f
INNER JOIN GOLD.DIM_DATE            od ON f.ORDER_DATE_KEY     = od.DATE_KEY
INNER JOIN GOLD.DIM_DATE            sd ON f.SHIP_DATE_KEY      = sd.DATE_KEY
INNER JOIN GOLD.DIM_SHIP_MODE       sm ON f.SHIP_MODE_KEY      = sm.SHIP_MODE_KEY
INNER JOIN GOLD.DIM_ORDER_PRIORITY  op ON f.ORDER_PRIORITY_KEY = op.ORDER_PRIORITY_KEY
INNER JOIN GOLD.DIM_LOCATION         l ON f.LOCATION_KEY       = l.LOCATION_KEY
WHERE f.IS_DELAYED = TRUE
ORDER BY
    EXCESS_DAYS DESC,
    f.SHIPPING_DURATION DESC;
