CREATE TABLE IF NOT EXISTS SHIPPING_DB.GOLD.DIM_ORDER_PRIORITY
(
    ORDER_PRIORITY_KEY  NUMBER IDENTITY(1,1),
    ORDER_PRIORITY      VARCHAR(30)     NOT NULL,
    CREATED_AT          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DIM_ORDER_PRIORITY PRIMARY KEY (ORDER_PRIORITY_KEY)
);
