CREATE TABLE IF NOT EXISTS SHIPPING_DB.GOLD.DIM_DATE
(
    DATE_KEY        NUMBER          NOT NULL,
    FULL_DATE       DATE            NOT NULL,
    DAY_NUMBER      NUMBER          NOT NULL,
    DAY_NAME        VARCHAR(20)     NOT NULL,
    DAY_OF_WEEK     NUMBER          NOT NULL,
    WEEK_NUMBER     NUMBER          NOT NULL,
    MONTH_NUMBER    NUMBER          NOT NULL,
    MONTH_NAME      VARCHAR(20)     NOT NULL,
    QUARTER_NUMBER  NUMBER          NOT NULL,
    YEAR_NUMBER     NUMBER          NOT NULL,
    IS_WEEKEND      BOOLEAN         NOT NULL,
    CREATED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DIM_DATE PRIMARY KEY (DATE_KEY)
);
