CREATE TABLE IF NOT EXISTS SHIPPING_DB.GOLD.DIM_SHIP_MODE
(
    SHIP_MODE_KEY   NUMBER IDENTITY(1,1),
    SHIP_MODE       VARCHAR(50)     NOT NULL,
    CREATED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DIM_SHIP_MODE PRIMARY KEY (SHIP_MODE_KEY)
);
