CREATE TABLE IF NOT EXISTS SHIPPING_DB.GOLD.DIM_LOCATION
(
    LOCATION_KEY    NUMBER IDENTITY(1,1),
    COUNTRY         VARCHAR(100)    NOT NULL,
    STATE           VARCHAR(100),
    CITY            VARCHAR(100),
    REGION          VARCHAR(100)    NOT NULL,
    MARKET          VARCHAR(100),
    CREATED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DIM_LOCATION PRIMARY KEY (LOCATION_KEY)
);
