MERGE INTO SHIPPING_DB.GOLD.DIM_ORDER_PRIORITY tgt
USING
(
    SELECT DISTINCT ORDER_PRIORITY
    FROM   SHIPPING_DB.SILVER.SILVER_SUPERSTORE
    WHERE  ORDER_PRIORITY IS NOT NULL
) src
ON tgt.ORDER_PRIORITY = src.ORDER_PRIORITY

WHEN NOT MATCHED THEN INSERT (ORDER_PRIORITY)
VALUES (src.ORDER_PRIORITY);
