MERGE INTO SHIPPING_DB.GOLD.DIM_SHIP_MODE tgt
USING
(
    SELECT DISTINCT SHIP_MODE
    FROM   SHIPPING_DB.SILVER.SILVER_SUPERSTORE
    WHERE  SHIP_MODE IS NOT NULL
) src
ON tgt.SHIP_MODE = src.SHIP_MODE

WHEN NOT MATCHED THEN INSERT (SHIP_MODE)
VALUES (src.SHIP_MODE);
