MERGE INTO SHIPPING_DB.GOLD.DIM_LOCATION tgt
USING
(
    SELECT DISTINCT
        COUNTRY,
        COALESCE(STATE,  '') AS STATE,
        COALESCE(CITY,   '') AS CITY,
        REGION,
        MARKET
    FROM SHIPPING_DB.SILVER.SILVER_SUPERSTORE
    WHERE COUNTRY IS NOT NULL
      AND REGION  IS NOT NULL
) src
ON  tgt.COUNTRY = src.COUNTRY
AND tgt.STATE   = src.STATE
AND tgt.CITY    = src.CITY
AND tgt.REGION  = src.REGION

WHEN NOT MATCHED THEN INSERT
(
    COUNTRY, STATE, CITY, REGION, MARKET
)
VALUES
(
    src.COUNTRY, src.STATE, src.CITY, src.REGION, src.MARKET
);
