INSERT INTO SHIPPING_DB.GOLD.DIM_DATE
(
    DATE_KEY,
    FULL_DATE,
    DAY_NUMBER,
    DAY_NAME,
    DAY_OF_WEEK,
    WEEK_NUMBER,
    MONTH_NUMBER,
    MONTH_NAME,
    QUARTER_NUMBER,
    YEAR_NUMBER,
    IS_WEEKEND
)

WITH NEW_DATES AS
(
    SELECT DISTINCT ORDER_DATE AS DT FROM SHIPPING_DB.SILVER.SILVER_SUPERSTORE WHERE ORDER_DATE IS NOT NULL
    UNION
    SELECT DISTINCT SHIP_DATE  AS DT FROM SHIPPING_DB.SILVER.SILVER_SUPERSTORE WHERE SHIP_DATE  IS NOT NULL
),

DATE_BOUNDS AS
(
    SELECT MIN(DT) AS MIN_DATE, MAX(DT) AS MAX_DATE FROM NEW_DATES
),

DATE_SPINE AS
(
    SELECT
        DATEADD(DAY, ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1, b.MIN_DATE) AS FULL_DATE
    FROM DATE_BOUNDS b,
         TABLE(GENERATOR(ROWCOUNT => 10000))
)

SELECT
    TO_NUMBER(TO_CHAR(FULL_DATE, 'YYYYMMDD'))   AS DATE_KEY,
    FULL_DATE,
    DAY(FULL_DATE)                              AS DAY_NUMBER,
    DAYNAME(FULL_DATE)                          AS DAY_NAME,
    DAYOFWEEK(FULL_DATE)                        AS DAY_OF_WEEK,
    WEEKOFYEAR(FULL_DATE)                       AS WEEK_NUMBER,
    MONTH(FULL_DATE)                            AS MONTH_NUMBER,
    MONTHNAME(FULL_DATE)                        AS MONTH_NAME,
    QUARTER(FULL_DATE)                          AS QUARTER_NUMBER,
    YEAR(FULL_DATE)                             AS YEAR_NUMBER,
    CASE WHEN DAYOFWEEK(FULL_DATE) IN (1, 7) THEN TRUE ELSE FALSE END AS IS_WEEKEND
FROM DATE_SPINE, DATE_BOUNDS
WHERE FULL_DATE <= DATE_BOUNDS.MAX_DATE
  AND TO_NUMBER(TO_CHAR(FULL_DATE, 'YYYYMMDD')) NOT IN (SELECT DATE_KEY FROM SHIPPING_DB.GOLD.DIM_DATE);
