MERGE INTO SHIPPING_DB.GOLD.FACT_SHIPPING tgt
USING
(
    WITH BASE AS
    (
        SELECT
            s.ORDER_ID,
            TO_NUMBER(TO_CHAR(s.ORDER_DATE, 'YYYYMMDD'))    AS ORDER_DATE_KEY,
            TO_NUMBER(TO_CHAR(s.SHIP_DATE,  'YYYYMMDD'))    AS SHIP_DATE_KEY,
            l.LOCATION_KEY,
            sm.SHIP_MODE_KEY,
            op.ORDER_PRIORITY_KEY,
            DATEDIFF(DAY, s.ORDER_DATE, s.SHIP_DATE)        AS SHIPPING_DURATION,
            s.SHIPPING_COST
        FROM SHIPPING_DB.SILVER.SILVER_SUPERSTORE s
        INNER JOIN SHIPPING_DB.GOLD.DIM_LOCATION l
            ON  s.COUNTRY               = l.COUNTRY
            AND COALESCE(s.STATE,  '')  = l.STATE
            AND COALESCE(s.CITY,   '')  = l.CITY
            AND s.REGION                = l.REGION
        INNER JOIN SHIPPING_DB.GOLD.DIM_SHIP_MODE sm
            ON s.SHIP_MODE = sm.SHIP_MODE
        INNER JOIN SHIPPING_DB.GOLD.DIM_ORDER_PRIORITY op
            ON s.ORDER_PRIORITY = op.ORDER_PRIORITY
        WHERE DATEDIFF(DAY, s.ORDER_DATE, s.SHIP_DATE) >= 0
        QUALIFY ROW_NUMBER() OVER (PARTITION BY s.ORDER_ID ORDER BY s.LOAD_TIMESTAMP DESC NULLS LAST) = 1
    ),

    WITH_MEDIAN AS
    (
        SELECT
            *,
            PERCENTILE_CONT(0.5)
                WITHIN GROUP (ORDER BY SHIPPING_DURATION)
                OVER (PARTITION BY SHIP_MODE_KEY) AS SHIPPING_DURATION_MEDIAN_BY_MODE
        FROM BASE
    )

    SELECT
        ORDER_ID,
        ORDER_DATE_KEY,
        SHIP_DATE_KEY,
        LOCATION_KEY,
        SHIP_MODE_KEY,
        ORDER_PRIORITY_KEY,
        SHIPPING_DURATION,
        SHIPPING_DURATION_MEDIAN_BY_MODE,
        CASE WHEN SHIPPING_DURATION > SHIPPING_DURATION_MEDIAN_BY_MODE THEN TRUE ELSE FALSE END AS IS_DELAYED,
        SHIPPING_COST
    FROM WITH_MEDIAN
) src
ON tgt.ORDER_ID = src.ORDER_ID

WHEN MATCHED THEN UPDATE SET
    ORDER_DATE_KEY                   = src.ORDER_DATE_KEY,
    SHIP_DATE_KEY                    = src.SHIP_DATE_KEY,
    LOCATION_KEY                     = src.LOCATION_KEY,
    SHIP_MODE_KEY                    = src.SHIP_MODE_KEY,
    ORDER_PRIORITY_KEY               = src.ORDER_PRIORITY_KEY,
    SHIPPING_DURATION                = src.SHIPPING_DURATION,
    SHIPPING_DURATION_MEDIAN_BY_MODE = src.SHIPPING_DURATION_MEDIAN_BY_MODE,
    IS_DELAYED                       = src.IS_DELAYED,
    SHIPPING_COST                    = src.SHIPPING_COST,
    LOAD_TIMESTAMP                   = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT
(
    ORDER_ID, ORDER_DATE_KEY, SHIP_DATE_KEY, LOCATION_KEY,
    SHIP_MODE_KEY, ORDER_PRIORITY_KEY, SHIPPING_DURATION,
    SHIPPING_DURATION_MEDIAN_BY_MODE, IS_DELAYED, SHIPPING_COST
)
VALUES
(
    src.ORDER_ID, src.ORDER_DATE_KEY, src.SHIP_DATE_KEY, src.LOCATION_KEY,
    src.SHIP_MODE_KEY, src.ORDER_PRIORITY_KEY, src.SHIPPING_DURATION,
    src.SHIPPING_DURATION_MEDIAN_BY_MODE, src.IS_DELAYED, src.SHIPPING_COST
);
