CREATE TABLE IF NOT EXISTS SHIPPING_DB.METADATA.PIPELINE_AUDIT
(
    RUN_ID              VARCHAR(100)    NOT NULL,
    PIPELINE_NAME       VARCHAR(200)    NOT NULL,
    BATCH_FILE          VARCHAR(500),
    STATUS              VARCHAR(20)     NOT NULL,
    START_TIME          TIMESTAMP_NTZ   NOT NULL,
    END_TIME            TIMESTAMP_NTZ,
    DURATION_SECONDS    NUMBER(10, 2),
    ERROR_MESSAGE       VARCHAR(4000),
    BRONZE_ROWS         NUMBER,
    SILVER_ROWS         NUMBER,
    GOLD_ROWS           NUMBER,
    CREATED_AT          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);
