COPY INTO SHIPPING_DB.BRONZE.BRONZE_SUPERSTORE
(
    CATEGORY,
    CITY,
    COUNTRY,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    DISCOUNT,
    MARKET,
    JI_LU_SHU,
    ORDER_DATE,
    ORDER_ID,
    ORDER_PRIORITY,
    PRODUCT_ID,
    PRODUCT_NAME,
    PROFIT,
    QUANTITY,
    REGION,
    ROW_ID,
    SALES,
    SEGMENT,
    SHIP_DATE,
    SHIP_MODE,
    SHIPPING_COST,
    STATE,
    SUB_CATEGORY,
    ORDER_YEAR,
    MARKET2,
    WEEKNUM
)
FROM @SHIPPING_DB.BRONZE.RAW_STAGE
FILE_FORMAT = (FORMAT_NAME = SHIPPING_DB.BRONZE.CSV_FILE_FORMAT)
PATTERN     = '.*batch_.*\\.csv\\.gz'
ON_ERROR    = CONTINUE;
