CREATE SCHEMA IF NOT EXISTS SHIPPING_DB.COMMON;
CREATE SCHEMA IF NOT EXISTS SHIPPING_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS SHIPPING_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS SHIPPING_DB.GOLD;
CREATE SCHEMA IF NOT EXISTS SHIPPING_DB.REPORTS;
CREATE SCHEMA IF NOT EXISTS SHIPPING_DB.METADATA;
